trigger:
  branches: main  # Trigger on main branch changes

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Deploy
    jobs:
      - job: DeployDAG
        steps:
          - task: DownloadSecureFile@1
            name: sshKey
            displayName: "Download SSH Key"
            inputs:
              secureFile: "id_rsa"  # Secure File uploaded in DevOps

          - script: |
              mkdir -p ~/.ssh
              cp $(sshKey.secureFilePath) ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
              echo "Host vps" >> ~/.ssh/config
              echo "  HostName $(SERVER_IP)" >> ~/.ssh/config
              echo "  User $(SERVER_USER)" >> ~/.ssh/config
              echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
              echo "  StrictHostKeyChecking no" >> ~/.ssh/config
              chmod 600 ~/.ssh/config
            displayName: "Setup Secure SSH Config"

          - script: |
              scp -r dags/* vps:/opt/airflow/dags/
            displayName: "Deploy DAG to SERVER"

          - script: |
              ssh vps "airflow dags trigger etl_pipeline"
            displayName: "Trigger DAG Reload"
